var mi_btn1 = document.querySelector('.mi_btn1');
var mi_mid1 = document.querySelector('.mi_mid1');
var mi_btn2 = document.querySelector('.mi_btn2');
var mi_mid2 = document.querySelector('.mi_mid2');
var mi_btn3 = document.querySelector('.mi_btn3');
var mi_mid3 = document.querySelector('.mi_mid3');
var mi_btn4 = document.querySelector('.mi_btn4');
var mi_mid4 = document.querySelector('.mi_mid4');
var mi_btn5 = document.querySelector('.mi_btn5');
var mi_mid5 = document.querySelector('.mi_mid5');
var mi_btn6 = document.querySelector('.mi_btn6');
var mi_mid6 = document.querySelector('.mi_mid6');
var mi_btn7 = document.querySelector('.mi_btn7');
var mi_mid7 = document.querySelector('.mi_mid7');
var mi_btn8 = document.querySelector('.mi_btn8');
var mi_mid8 = document.querySelector('.mi_mid8');
var mi_main = document.querySelector('.mi_main');

mi_btn1.addEventListener('click', function (){
    mi_mid1.style.display = 'block';
    mi_mid2.style.display = 'none';
    mi_mid3.style.display = 'none';
    mi_mid4.style.display = 'none';
    mi_mid5.style.display = 'none';
    mi_mid6.style.display = 'none';
    mi_mid7.style.display = 'none';
    mi_mid8.style.display = 'none';
    mi_btn1.style.color = '#ffffff';
    mi_btn2.style.color = '#ff962a';
    mi_btn3.style.color = '#ff962a';
    mi_btn4.style.color = '#ff962a';
    mi_btn5.style.color = '#ff962a';
    mi_btn6.style.color = '#ff962a';
    mi_btn7.style.color = '#ff962a';
    mi_btn8.style.color = '#ff962a';
    mi_btn1.style.backgroundImage = "url(./imgs/botton_hover.png)";
    mi_btn2.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn3.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn4.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn5.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn6.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn7.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn8.style.backgroundImage = "url(./imgs/botton.png)";
    mi_main.style.background = "url(./imgs/data_f2.png) center center no-repeat";
});

mi_btn2.addEventListener('click', function (){
    mi_mid2.style.display = 'block';
    mi_mid1.style.display = 'none';
    mi_mid3.style.display = 'none';
    mi_mid4.style.display = 'none';
    mi_mid5.style.display = 'none';
    mi_mid6.style.display = 'none';
    mi_mid7.style.display = 'none';
    mi_mid8.style.display = 'none';
    mi_btn2.style.color = '#ffffff';
    mi_btn1.style.color = '#ff962a';
    mi_btn3.style.color = '#ff962a';
    mi_btn4.style.color = '#ff962a';
    mi_btn5.style.color = '#ff962a';
    mi_btn6.style.color = '#ff962a';
    mi_btn7.style.color = '#ff962a';
    mi_btn8.style.color = '#ff962a';
    mi_btn2.style.backgroundImage = "url(./imgs/botton_hover.png)";
    mi_btn1.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn3.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn4.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn5.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn6.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn7.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn8.style.backgroundImage = "url(./imgs/botton.png)";
});

mi_btn3.addEventListener('click', function (){
    mi_mid3.style.display = 'block';
    mi_mid2.style.display = 'none';
    mi_mid1.style.display = 'none';
    mi_mid4.style.display = 'none';
    mi_mid5.style.display = 'none';
    mi_mid6.style.display = 'none';
    mi_mid7.style.display = 'none';
    mi_mid8.style.display = 'none';
    mi_btn3.style.color = '#ffffff';
    mi_btn2.style.color = '#ff962a';
    mi_btn1.style.color = '#ff962a';
    mi_btn4.style.color = '#ff962a';
    mi_btn5.style.color = '#ff962a';
    mi_btn6.style.color = '#ff962a';
    mi_btn7.style.color = '#ff962a';
    mi_btn8.style.color = '#ff962a';
    mi_btn3.style.backgroundImage = "url(./imgs/botton_hover.png)";
    mi_btn2.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn1.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn4.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn5.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn6.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn7.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn8.style.backgroundImage = "url(./imgs/botton.png)";
    mi_main.style.background = "url(./imgs/data_f2.png) center center no-repeat";
});

mi_btn4.addEventListener('click', function (){
    mi_mid4.style.display = 'block';
    mi_mid2.style.display = 'none';
    mi_mid3.style.display = 'none';
    mi_mid1.style.display = 'none';
    mi_mid5.style.display = 'none';
    mi_mid6.style.display = 'none';
    mi_mid7.style.display = 'none';
    mi_mid8.style.display = 'none';
    mi_btn4.style.color = '#ffffff';
    mi_btn2.style.color = '#ff962a';
    mi_btn3.style.color = '#ff962a';
    mi_btn1.style.color = '#ff962a';
    mi_btn5.style.color = '#ff962a';
    mi_btn6.style.color = '#ff962a';
    mi_btn7.style.color = '#ff962a';
    mi_btn8.style.color = '#ff962a';
    mi_btn4.style.backgroundImage = "url(./imgs/botton_hover.png)";
    mi_btn2.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn3.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn1.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn5.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn6.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn7.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn8.style.backgroundImage = "url(./imgs/botton.png)";
});

mi_btn5.addEventListener('click', function (){
    mi_mid5.style.display = 'block';
    mi_mid2.style.display = 'none';
    mi_mid3.style.display = 'none';
    mi_mid4.style.display = 'none';
    mi_mid1.style.display = 'none';
    mi_mid6.style.display = 'none';
    mi_mid7.style.display = 'none';
    mi_mid8.style.display = 'none';
    mi_btn5.style.color = '#ffffff';
    mi_btn2.style.color = '#ff962a';
    mi_btn3.style.color = '#ff962a';
    mi_btn4.style.color = '#ff962a';
    mi_btn1.style.color = '#ff962a';
    mi_btn6.style.color = '#ff962a';
    mi_btn7.style.color = '#ff962a';
    mi_btn8.style.color = '#ff962a';
    mi_btn5.style.backgroundImage = "url(./imgs/botton_hover.png)";
    mi_btn2.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn3.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn4.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn1.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn6.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn7.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn8.style.backgroundImage = "url(./imgs/botton.png)";
});

mi_btn6.addEventListener('click', function (){
    mi_mid6.style.display = 'block';
    mi_mid2.style.display = 'none';
    mi_mid3.style.display = 'none';
    mi_mid4.style.display = 'none';
    mi_mid5.style.display = 'none';
    mi_mid1.style.display = 'none';
    mi_mid7.style.display = 'none';
    mi_mid8.style.display = 'none';
    mi_btn6.style.color = '#ffffff';
    mi_btn2.style.color = '#ff962a';
    mi_btn3.style.color = '#ff962a';
    mi_btn4.style.color = '#ff962a';
    mi_btn5.style.color = '#ff962a';
    mi_btn1.style.color = '#ff962a';
    mi_btn7.style.color = '#ff962a';
    mi_btn8.style.color = '#ff962a';
    mi_btn6.style.backgroundImage = "url(./imgs/botton_hover.png)";
    mi_btn2.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn3.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn4.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn5.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn1.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn7.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn8.style.backgroundImage = "url(./imgs/botton.png)";
});

mi_btn7.addEventListener('click', function (){
    mi_mid7.style.display = 'block';
    mi_mid2.style.display = 'none';
    mi_mid3.style.display = 'none';
    mi_mid4.style.display = 'none';
    mi_mid5.style.display = 'none';
    mi_mid6.style.display = 'none';
    mi_mid1.style.display = 'none';
    mi_mid8.style.display = 'none';
    mi_btn7.style.color = '#ffffff';
    mi_btn2.style.color = '#ff962a';
    mi_btn3.style.color = '#ff962a';
    mi_btn4.style.color = '#ff962a';
    mi_btn5.style.color = '#ff962a';
    mi_btn6.style.color = '#ff962a';
    mi_btn1.style.color = '#ff962a';
    mi_btn8.style.color = '#ff962a';
    mi_btn7.style.backgroundImage = "url(./imgs/botton_hover.png)";
    mi_btn2.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn3.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn4.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn5.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn6.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn1.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn8.style.backgroundImage = "url(./imgs/botton.png)";
});

mi_btn8.addEventListener('click', function (){
    mi_mid8.style.display = 'block';
    mi_mid2.style.display = 'none';
    mi_mid3.style.display = 'none';
    mi_mid4.style.display = 'none';
    mi_mid5.style.display = 'none';
    mi_mid6.style.display = 'none';
    mi_mid7.style.display = 'none';
    mi_mid1.style.display = 'none';
    mi_btn8.style.color = '#ffffff';
    mi_btn2.style.color = '#ff962a';
    mi_btn3.style.color = '#ff962a';
    mi_btn4.style.color = '#ff962a';
    mi_btn5.style.color = '#ff962a';
    mi_btn6.style.color = '#ff962a';
    mi_btn7.style.color = '#ff962a';
    mi_btn1.style.color = '#ff962a';
    mi_btn8.style.backgroundImage = "url(./imgs/botton_hover.png)";
    mi_btn2.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn3.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn4.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn5.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn6.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn7.style.backgroundImage = "url(./imgs/botton.png)";
    mi_btn1.style.backgroundImage = "url(./imgs/botton.png)";
    mi_main.style.background = "url(./imgs/data_f2.png) center center no-repeat";
});